### ISSUE TITLE
"Retry" leads to indefinitely pending files  

### ISSUE THREAD

**Issue by fabianneuhaus** [ontohub/ontohub#1019]
I "retried" files that caused an error before (see bug #982), but from what I can tell so far this just leads to indefinitely pending files. At least so far, nothing happens (>20 minutes). 
https://ontohub.org/repositories/bfo/errors
The server does not seem busy, since changes to other files are parsed immediately. It does not seem to make a difference whether I just press the "Retry All" button or select an individual file.

**Comment by tillmo** [comment]
should be solved by #1557

**Comment by eugenk** [comment]
I just tested this on ontohub.org. It is not an issue any more.
