### ISSUE TITLE
WebSocket for direct communication with Hets?

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#114]
http://en.wikipedia.org/wiki/WebSocket

**Comment by 0robustus1** [comment]
First Hets would need to implement WebSocket capabilities (and a corresponding API based on the RESTful API). This would probably take a lot of time, seeing as the team is currently short-staffed.

Additionally WebSockets are only really useful if we were to have big session-like features. Like corny suggested those usually are services like chats or other collaboration features. I currently do not see the need for this in Hets. Additionally hets would need to be able to process these things asynchronously (which it currently does not). I would advise against this.

**Comment by tillmo** [comment]
agreed
