### ISSUE TITLE
mail settings do not work

### ISSUE THREAD

**Issue by jelmd** [ontohub/ontohub#1142]
Trying to configure ontohub to use :smtp, however, it doesn't seem to work (gets overwritten somewhere?).

I already set "delivery_method: smtp" in config/settings.yml and put the following snippet into
 config/application.rb as well as config/environments/*.rb

config.action_mailer.smtp_settings = { 
        :address        => "mail", 
        :port           => 25, 
        :enable_starttls_auto   => false 
 }

The log says:
...
Sent mail to ex+oh-tb@iws.cs.ovgu.de (6.4ms)
An error occurred when sending a notification using 'email' notifier. Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 25
...

**Comment by tillmo** [comment]
should work now
