### ISSUE TITLE
god doesn't reliable terminate workers

### ISSUE THREAD

**Issue by jelmd** [ontohub/ontohub#1150]
"god terminate" does a very poor job and always leaves sidekiq workers running often all-1|2 (leaks ~32x256MiB ~= 8GiB RAM RSS) even when they are all idle! 

Furthermore it would be nice, if one could configure, how many sidekiq workers get spawned by god. The current default (nrpoc+4?) seems to be inappropriate. My rule of thumb says, nproc*(0.75+-0.05) would be more healthy for a system.

**Comment by eugenk** [comment]
We will introduce a new option in the configuration file which lets the admin configure how many hets workers are created.
