### ISSUE TITLE
bug: undefined method `up?' for nil:NilClass

### ISSUE THREAD

**Issue by jelmd** [ontohub/ontohub#1151]
Just tried to mirror git://ontohub.org/animal_monster.git - but there seems to be an error wrt. hets (see http://tb.iws.cs.ovgu.de/repositories/bla aka staging.ontohub.org branch):

```
2014-12-28T00:58:31.968Z 21200 TID-ovg04zl9k WARN: {"retry"=>false, "queue"=>"hets", "class"=>"OntologyBatchParseWorker", "args"=>[nil, [[41, {"fast_parse"=>false}]], {"try_count"=>1}], "jid"=>"be4c7f40fe701317efbe627e", "enqueued_at"=>1419728311.9313483, "error_message"=>"undefined method `up?' for nil:NilClass", "error_class"=>"NoMethodError", "processor"=>"tb:21200", "failed_at"=>1419728311.9676225}
2014-12-28T00:58:31.968Z 21200 TID-ovg04zl9k WARN: undefined method `up?' for nil:NilClass
2014-12-28T00:58:31.968Z 21200 TID-ovg04zl9k WARN: /local/home/ontohub/ontohub/lib/hets/parse_caller.rb:18:in `initialize'
/local/home/ontohub/ontohub/lib/hets.rb:104:in `new'
/local/home/ontohub/ontohub/lib/hets.rb:104:in `parse_via_api'
/local/home/ontohub/ontohub/app/models/ontology_version/parsing.rb:46:in `generate_xml'
/local/home/ontohub/ontohub/app/models/ontology_version/parsing.rb:34:in `block in parse'
/local/home/ontohub/ontohub/lib/state_updater.rb:20:in `do_or_set_failed'
/local/home/ontohub/ontohub/app/models/ontology_version/parsing.rb:32:in `parse'
/local/home/ontohub/ontohub/lib/ontology_batch_parse_worker.rb:33:in `execute_perform'
/local/home/ontohub/ontohub/lib/ontology_batch_parse_worker.rb:16:in `perform'
```

**Comment by tillmo** [comment]
Of course you can do everything that capistrano does also with a shell script. However, capistrano can simplify many things, especially since you can easily iterate over a server list (note that we want to set up spechub.org, logichub.org etc.), you have a tight integration with ruby and concise syntax for various hooks. Moreover, you have a community creating and testing capistrano recipes, such that you do not need to reinvent the wheel.
Concerning the error thrown by Ontohub, I agree that Ontohub should catch it somehow. Could someone please comment on this?

**Comment by tillmo** [comment]
btw: happy new year!

**Comment by jelmd** [comment]
Dito :)

Since td (the passenger based setup) didn't get used, I replaced it with the latest setup, i.e. it is a vanilla develop...instance. As said, you should be able to login as ontohub (or admin if you need more privileges). ~ontohub/ontohub contains the repo. Important data are below /data , logs in ~ontohub[/ontohub]/log and /var/log. Having a look at ~admin/etc/oh-update.sh should reveal all the details. On this machine only user ontohub should use it (apache setup etc. is wired to ~ontohub ...).

**Comment by 0robustus1** [comment]
Ok. The problem seems to be the following. Recently the hets-Team added the *hets-server* package, which you installed. But *hets-server* only has the `hets-server` binary/script, whereas our scripts and config (especially god) rely on the `hets` binary/script. So adding a symlink called `hets` to `hets-server` should resolve the problem (You'll need to tell god to restart hets).
Actually that is also why the rake-task (and capistrano) failed, because this actually performs a check if the hets-instance is running.

**Comment by tillmo** [comment]
eventually, we will give up the binary name `hets-server` and the symlink won't be necessary, see https://github.com/spechub/Hets/issues/1440

**Comment by jelmd** [comment]
Strange, I thought, I've already caught all hets calls (see the git diff below). Are there other places I missed? Or do `hets` and `hets-server` behave differently? BTW: Wouldn't it make sense to define the binary to be called in exactly one place (could be relevant for adhoc testing as well)?

```diff
diff --git a/config/hets.yml b/config/hets.yml
index b17bfda..79d7408 100644
--- a/config/hets.yml
+++ b/config/hets.yml
@@ -1,30 +1,10 @@
 # Hets environment. The first matching item in the lists is used.
 hets_path:
-  - /usr/bin/hets
-  - ~/dev/hets/hets
-  - /opt/local/bin/hets
-  - ~/code/hets/hets
-  - ~/ontohub/Hets/hets
-  - /usr/local/opt/hets/bin/hets-bin
-  - /usr/local/opt/hets/bin/hets
-  - /usr/local/opt/hets-binary/Hets.app/Contents/Resources/hets
-  - /Applications/Hets.app/Contents/Resources/hets
+  - /usr/bin/hets-server
 hets_lib:
-  - /usr/lib/hets/hets-lib
-  - ~/dev/hets/lib
-  - ~/ontohub/Hets
-  - /usr/local/opt/hets-lib
-  - /usr/local/opt/hets-binary/Hets.app/Contents/Resources/Hets-lib
-  - /Applications/Hets.app/Contents/Resources/Hets-lib
-  - /opt/hets-lib
+  - /usr/lib/hets-server
 hets_owl_tools:
-  - /usr/lib/hets/hets-owl-tools
-  - ~/dev/hets/OWL2
-  - ~/code/hets/OWL2
-  - ~/ontohub/Hets/OWL2
-  - /usr/local/opt/hets/lib/hets-owl-tools/
-  - /usr/local/opt/hets-binary/Hets.app/Contents/Resources/hets-owl-tools
-  - /Applications/Hets.app/Contents/Resources/hets-owl-tools
+  - /usr/lib/hets-server/hets-owl-tools

 version_minimum_version: 0.99
 version_minimum_revision: 1409841736
diff --git a/lib/tasks/hets.rake b/lib/tasks/hets.rake
index 053bef2..cbd68bb 100644
--- a/lib/tasks/hets.rake
+++ b/lib/tasks/hets.rake
@@ -2,7 +2,7 @@ namespace :hets do

   HETS_LOGFILE = Rails.root.join('log', 'hets.log')
   HETS_PIDFILE = Rails.root.join('tmp', 'pids', 'hets.pid')
-  HETS_CMD = "hets -X"
+  HETS_CMD = "hets-server -X"

   desc "Create Hets Instance if neccessary"
   task :generate_first_instance => :environment do
diff --git a/lib/tasks/test.rake b/lib/tasks/test.rake
index 90a7b88..b3a1809 100644
--- a/lib/tasks/test.rake
+++ b/lib/tasks/test.rake
@@ -32,7 +32,7 @@ namespace :test do

   def perform_hets_on(file)
     args = hets_args << '-O test/fixtures/ontologies/hets-out'
-    system("hets #{args.join(' ')} #{file}")
+    system("hets-server #{args.join(' ')} #{file}")
   end

   def ontology_files
```

**Comment by 0robustus1** [comment]
@jelmd, please just symlink the binary instead of changing the ontohub code.

**Comment by tillmo** [comment]
Three things:
* please follow the standard setup (using capistrano) that is used by Ontohub, this avoids the chicken-egg problem that you mention and makes debugging easier for the team, because everyone uses the same thing.
* the error is probably caused by Hets not being able to download a URL
* in order to properly debug the above error, the team needs access to tb. Currently, we only have access to td.

**Comment by tillmo** [comment]
@jelmd, the Ontohub team cannot debug anything, because td is down. Is the bare metal machine up? Is there a status page for the servers at IWS?

**Comment by jelmd** [comment]
Yes, however as long  as I didn't got a 'Go' I keep the t*.ontohub.org on a RAM disk (saves time because it makes zone destroy/create faster). The downside is, they vanish on re-boot (updates) and need to be re-created on demand.

24/7 shouldn't be a problem. 'til now (beside of one broken HDD) I haven't seen any HW issues. Our Solaris based Server with similar HW have "three nines" uptime, without updates (~ every 3 month) they would have "five nines". So depends mainly on how often updates are done.

**Comment by tillmo** [comment]
For now, it would suffice to keep just one of them up 24/7, so that the team can always take a look at details.

**Comment by jelmd** [comment]
OK, pushed the td to persistent store, i.e. HDD JBOD. If it needs to be included into the backups, plz give me a hint (currently working on proper packaging the netbackup SW - should be ready for testing tomorrow +-1).

If you wanna check, how it gets currently build, you can also do as user ontohub:
```rm -rf ~/ontohub && ~admin/etc/oh-update.sh```

**Comment by tillmo** [comment]
td.isw.cs.ovgu.de is not reachable

**Comment by jelmd** [comment]
typo: use iws instead of isw

**Comment by tillmo** [comment]
sorry, now it works

**Comment by jelmd** [comment]
OK. BTW: t[a-d].iws.cs.... is just an alias for  t[a-d].ontohub.org (convenience for lazy "typers" ;-) ).

**Comment by tillmo** [comment]
I can reproduce this bug on staging.ontohub.org. See http://staging.ontohub.org/repositories/test3/errors and http://staging.ontohub.org/repositories/test/ontologies/88/versions. It seems that all newly uploaded ontologies produce this error.

**Comment by eugenk** [comment]
This seems to have come with #1162. I have part of a fix at #1189.

The other part is updating hets to the current version and restarting hets. I needed to do this on develop.ontohub.org, because it requires a more recent minimal version. I don't know why, but I needed to destroy every `HetsInstance` in the database and run `rake hets:generate_first_instance` to make it work.

**Comment by 0robustus1** [comment]
Every instance? Shouldn't there be only one? A reason for this is, because we currently do not implement automatic version-update checks. I've planned this as part of hets-error handling.

**Comment by eugenk** [comment]
There were two instances in the database, but only one hets process running.

**Comment by tillmo** [comment]
@jelmd, could you try and see whether your problem has been solved now? (actually, first staging needs to be merged into staging.ontohub.org, @eugenk, can you do that?)

**Comment by eugenk** [comment]
It's merged

**Comment by jelmd** [comment]
Good question - I can't say. http://tb.iws.cs.ovgu.de/repositories/bla/errors shows now `failed: Can't follow the response from http://localhost:8000/dg/http%3A%2F%2Fstaging.ontohub.org%2Fref%2F1%2Fbla%2Fbear/full-signatures/full-theories/auto anymore.`

I made a complete fresh setup, i.e. incl. removal of the web, git store & DBs (aka rm -rf /data/*) to get rid off other strange errors and mirrored git://ontohub.org/animal_monster.git .

**Comment by tillmo** [comment]
This problem has been reported in #1199.
