### ISSUE TITLE
Add creation of combined ontology to API

### ISSUE THREAD

**Issue by 0robustus1** [ontohub/ontohub#1156]
Like #150 will create a user-interfaced version of combined ontology creation, the API should also
include a version of that.

**Comment by 0robustus1** [comment]
@tillmo This basically means creating a distributed ontology in DOL which will contain the combine-command, correct?
Where can i find the version of the DOL standard that is currently supported by hets?

**Comment by tillmo** [comment]
correct. The DOL standard is available at https://github.com/tillmo/DOL
