### ISSUE TITLE
integrate Selenium IDE, generate capybara tests

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1157]
The goal is to use the [Selenium IDE] (http://www.seleniumhq.org/projects/ide/) for writing integration tests (anyone knowing ontohub can write such tests, no need to learn Rails). From the Selenium IDE tests, use the [Selenium XML Formatter] (http://docs.seleniumhq.org/download/#side_plugins) to extract an XML data structure. Convert this to capybara tests.

**Comment by ebolloff** [comment]
Which tests should be generated with the capybara commands? Cucumber?

**Comment by tillmo** [comment]
it could be based on cucumber, but then one needs probably more input from the user to generate the cucmber text. Originally I thought just of rspec tests using capybara.

**Comment by jagtesh** [comment]
Any progress on this guys? Would love to see some code. I can volunteer to test and contribute. Rspec is good enough for my purposes.

**Comment by ebolloff** [comment]
Actually this the subject for my bachelor thesis which I'm working on right now. So in a few months it'll hopefully be integrated in Ontohub.

**Comment by ebolloff** [comment]
@jagtesh have a look at the gem [featurecorder](https://github.com/ebolloff/featurecorder) and mail me, if you have questions
