### ISSUE TITLE
'Create Repository' feature is not working

### ISSUE THREAD

**Issue by hardik101** [ontohub/ontohub#1159]
Clicking on 'Creating Repository' button after entering respective data in form is taking indefinite time to  load. (Tested it twice for at least 10 minute and it doesn't work.)
![screenshot from 2015-01-15 19 53 53](https://cloud.githubusercontent.com/assets/1309118/5764179/67c24f68-9cf0-11e4-8c90-6265e40b0303.png)

**Comment by 0robustus1** [comment]
Creating a Repository works. Your problem might be with creating a mirror repository.

**Comment by eugenk** [comment]
For me, all three cases work perfectly fine (on ontohub.org - less than a second response time):
* Simple repository (no mirror)
* Mirror repository with correct source address
* Mirror repository with source address that does not point to a repository

**Comment by hardik101** [comment]
@0robustus1  you are right. issue I am having  is only with mirrored repository.
I have tested it for : 
1.Simple repository (no mirror) - it works
2.Mirror Repository (with valid github url) -doesn't work.

**Comment by eugenk** [comment]
Can you paste the url to the github repo you used for this?
At least for https://github.com/eugenk/cliftest.git it worked 20 minutes ago.

**Comment by hardik101** [comment]
I have used this url :   
https://github.com/hardik101/image-schema-formalization.git

**Comment by eugenk** [comment]
This doesn't work because it is a private repository. When trying to access it, the git client asks for user credentials and just waits for stdin.

It can't work for private github repositories since they're not accessible. However, ontohub should recognize this and not wait for sdtin. I will fix this.
