### ISSUE TITLE
Integrate parts of server config into Ontohub

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1170]
see https://gist.github.com/tillmo/a7cb0537bd41872b411a, where the diff is commented. Some diffs should be turned into branches (forking from staging), others should be avoided.
Moreover, here are some further hints for the server config:
* install dependencies: svn, git-svn
* entities errors: stem from migration executed in production mode
* switch to production mode; use symlink for hets instead of source patches

**Comment by jelmd** [comment]
After applying the follwoing patches, all customization (if needed at all now) can be done via config/settings.[local].yml and friends, so no patching of other files is required anymore:
```
  1170-frontend-notes
  1170-git-data_dir
  1170-hets-binary-path
  1170-puma-support
  1170-settings-cleanup
  common-settings-behavior
```
The latest https://github.com/ontohub/admin-scripts/tree/puma/scripts/install expect these patches to be installed or available as ~ontohub/etc/*.patch.

**Comment by eugenk** [comment]
This is not completed yet. Reopening.

**Comment by eugenk** [comment]
The pull requests #1241, #1266, 1268, #1269 and #1309 are part of this issue.

**Comment by tillmo** [comment]
we have decided to add puma to the Gemfile, as in @jelmd's pull request #1176. @eugenk, could you please create an appropriate pull request? (The puma config has already been added in #1241).
