### ISSUE TITLE
Add git-commit header-fields to ontology-version

### ISSUE THREAD

**Issue by 0robustus1** [ontohub/ontohub#1171]
Currently the Ontology-Versions only stores a reference to the commit-oid. If we were however to also
store committer, commit-date, author and author-date information we would be able to perform
rather fast queries on that data.

I'm proposing this because i'm currently working on implementing the Date-Range feature of LocIds (e.g.
`'http://ontohub.dev/ref/2015-01-27/default/partial_order//strict_partial_order'`). And even if we were to get that working with rugged, it would still be quite slow (which isn't very good for HTTP-Routing).

@eugenk as you are currently the one person with the most experience in rugged, what would be your take on this?

**Comment by eugenk** [comment]
From the top of my head, I'd use the `Repository#commits` iterator to get access to the rugged-commit objects in a rake task and store them in a `Commit` model, which is referenced by an ontology version (`OntologyVersion#commit_oid`).
