### ISSUE TITLE
better error message when I have no rights to write

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1183]
When I clone a repository and then trx to write without write permissions, I get "fatal: Could not read from remote repository.", which is a bit confusing, since I am trying to write:
```
> git push
Access denied.
Please take a look at
http://wiki.ontohub.org/index.php/Permission
for more information about permissions."
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
>
```

**Comment by 0robustus1** [comment]
`fatal: Could not read from remote repository` is output provided by git, not by us.
