### ISSUE TITLE
Parsing error "Can't follow the response from ... anymore."

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1199]
See http://develop.ontohub.org/repositories/casl-um/ontologies/357/versions : 
```
Can't follow the response from http://localhost:8000/dg/http%3A%2F%2Fdevelop.ontohub.org%2Fref%2F1%2Fcasl-um%2FSbcs/full-signatures/full-theories anymore.
```

Try to call hets with option "-a none". Perhaps this will solve the problem.

**Comment by eugenk** [comment]
Running this locally results in:
```
❯ curl http://localhost:8000/dg/http%3A%2F%2Fdevelop.ontohub.org%2Fref%2F1%2Fcasl-um%2FSbcs/full-signatures/full-theories
*** Error:
http://develop.ontohub.org/ref/1/casl-um/Sbcs:525.12:
unexpected "V"
expecting "%", ":" or "="
```
I assume this is being worked on in the hets-errors issue.

**Comment by tillmo** [comment]
@jelmd gets the same problem, appearantly with ontologies that are OK.

**Comment by tillmo** [comment]
see http://develop.ontohub.org/casl-um/new/Chapter3///ontology_versions

**Comment by 0robustus1** [comment]
Seems like there was something wrong with the running hets process. A restart fixed this.

**Comment by jelmd** [comment]
I'm still seeing exactly the same error on td (staging.ontohub.org).

**Comment by tillmo** [comment]
I reopen this issue because @jelmd has reproduced it on staging, although @eugenk writes: "now, we’re encountering the same error, as well. There are a few new features in the branch develop.ontohub.org which might be the reason for the problem. We’re working on it. I’ll let you know as soon as this is sorted out."

**Comment by jelmd** [comment]
just did a fresh setup of tb: same thing + postgres error. See http://tb.iws.cs.ovgu.de/repositories/bla/errors

**Comment by 0robustus1** [comment]
Is this still current/reproducible?

**Comment by 0robustus1** [comment]
Again, is this still current and/or reproducible?

**Comment by tillmo** [comment]
no, currently I cannot reproduce this.

**Comment by tillmo** [comment]
I get the error again (more precisely, `can't follow the response, and response not useable`), with https://ontohub.org/sandbox/dol-ontology
A local `hets -g http://ontohub.org/sandbox/dol-ontology` succeeds. Also, `curl localhost:8000/dg/http%3a%2f%2fontohub.org%2fsandbox%2fdol-ontology/full-signatures/full-theories/auto` succeeds.

**Comment by eugenk** [comment]
This is a Hets error, but I can't tell what exactly is wrong.

When executing
```
curl "http://localhost:8000/dg/http%3A%2F%2Fontohub.org%2Fref%2F1%2Fsandbox%2Fdol-ontology/full-signatures/full-theories/auto?url-catalog=http://colore.oor.net=http://ontohub.org/colore/ontologies;"
```
on ontohub.org, we get
```
Something went wrong
```
while I get the desired XML when executing the exact same command on my laptop.

**Comment by tillmo** [comment]
In order to get more than "Something went wrong", wait for https://github.com/spechub/Hets/issues/1522

**Comment by tillmo** [comment]
OK, with a fix for spechub/Hets#1522, we now get 
```
fd:11: hGetContents: invalid argument (invalid byte sequence)
```

**Comment by jelmd** [comment]
Perhaps a character encoding problem (e.g. UTF-8<->latin1)?

**Comment by tillmo** [comment]
The point is that this error only occurs on ontohub.org, not on our local machines. So I guess it is a language or locale problem on ontohub.org.  @jelmd, do you have an idea?

**Comment by jelmd** [comment]
Not sure, what haskell does, but usually apps/langVms use the LC_* env vars and some GNU apps even the LANG env var to "init" their char/message/"etc" handling if it not explicitly initialized by the app.

I guess, haskell has something like a getenv() call as well. Thus temp. I would add some code to the except. handling, which emits the env var values for LC_CTYPE, LC_MESSAGES and LANG (for lex. sorting LC_COLLATE,  LC_NUMERIC, LC_MONETARY might also be interesting) and compare them on ontohub.org and  "our local machines"...

**Comment by tillmo** [comment]
We have tested it. The problem is that we need `LANG=en_US.UTF-8`. Otherwise, the error occurs. On ontohub.org, hets obviously is run with `LANG`not set.

**Comment by jelmd** [comment]
Ohhh, assumed until now that this is the "system" default. But digging around I found out [or not ;-)], that there are no system defaults on ubuntu/upstart (e.g. like /etc/default/init). So I supplemented the ~ontohub/etc/*-serv.sh startup scripts accordingly. Hopefully it gets inherited down (instances already restarted) ...

BTW: There were and are again a bunch of postgresql processes (25 SELECT + 4 idle) related to ontohub, which consume in sum ~10+-1 full CPU threads (so about  1/3 of available threads or ~3/4 of all cores). This seems to be odd, because there are actually at most a 5-10 http requests/min) ...

**Comment by eugenk** [comment]
> BTW: There were and are again a bunch of postgresql processes (25 SELECT + 4 idle) related to ontohub, which consume in sum ~10+-1 full CPU threads (so about 1/3 of available threads or ~3/4 of all cores). This seems to be odd, because there are actually at most a 5-10 http requests/min) ...

This is being worked on. See #1450 and #1473

**Comment by tillmo** [comment]
Hm, the encoding error is still there, see https://ontohub.org/repositories/sandbox/ontologies/10629/versions

**Comment by jelmd** [comment]
Could it be, that whatever chomps the input is not multibyte aware (0xE9 results into 0xC3A9 - see ksh93: ` print -n '\0351' | iconv -f ISO8859-1 -t UTF-8 | xxd`).

**Comment by tillmo** [comment]
actually, this is a Hets problem, see https://github.com/spechub/Hets/issues/1531

**Comment by tillmo** [comment]
the Hets problem has been solved

**Comment by tillmo** [comment]
works now
