### ISSUE TITLE
hets.yml: version_minimum_version:, version_minimum_revision: don't make sense

### ISSUE THREAD

**Issue by jelmd** [ontohub/ontohub#1204]
In `config/hets.yml` version_minimum_version:, version_minimum_revision: don't make any sense, because if a user can set the "numbers" to compare to the version of the installed hets the corresponding check in [hets.rb] (https://github.com/ontohub/ontohub/blob/staging/lib/hets.rb#L56) is totally useless. Actually `config/hets.yml` implies to a casual user: adjust this if it doesn't match your environment ...

So if there are unresolvable compatibility problems, those numbers need to be hard coded into the application (binary) and nowhere else.

BTW: hets should start to use/obey [semantic versioning] (http://semver.org/) as well - using a  unix timestamp aka seconds since 01.01.1970 00:00:00 for comparision is very user friendly ;-)

**Comment by 0robustus1** [comment]
It is news to me that *config/hets.yml* is to be adjusted by the *user* (i am assuming that by *user* you actually mean: provider of an ontohub-instance). It is an internal configuration file.

Additionally: i've tried to get the hets-team to implement semantic versioning (or any versioning scheme), and they will employ something like this in the future, but this does not change the fact that ontohub is in development (as is hets) and will require certain bleeding edge features of hets. So we'll probably still use an additional timestamp value to refer to our specific version. But ontohub releases will probably refer to hets-releases.

**Comment by jelmd** [comment]
Well, actually it is not documented (the root cause of most trouble) and the term 'config' implies "adjust to your needs". If it is deemed to be internal, i.e. should not be touched by any user/"provider of an ontohub-instance", it should live somewhere below 'lib/' - at least that's the convention for most applications on *x and thus more natural/user friendly/easier to understand for the software user in terms of running it as a service (should we use the term "service provider" in general for this?) ... 

Anyway, I don't see any reason, why the file should be declared as 'internal'. But as said (and thus back to issue) IMHO the mentioned properties have to be an inner/hidden part of the application, do not belong to hets.yml.

**Comment by 0robustus1** [comment]
Usually the *user* of an application does not decide on the dependencies of said application, unless there were declared optional by the developers of said application. That is not is the case here, as hets is essential to the functionality of ontohub. Additionally: *conf/* is a rails standard/convention for such files, which is the reason why we place such files there.

As far as i know only the database.yml and the settings.yml (plus their environment-specific counterparts) are documented to be part of the deployment process, so i do not see why anyone would assume, that there are other files to be edited.

**Comment by jelmd** [comment]
Plz read my previous response again!

**Comment by tillmo** [comment]
hets.yml should not be touched by the user nor the admin, ony by developers. Hence, it is internal. Still, the rails convention is not to put it into lib/. This will be documented in doc/ in the course of issue #1155.

**Comment by tillmo** [comment]
Hets versioning is more a Hets issue, so we close this here.
