### ISSUE TITLE
Integrate documentation into the ontohub repository

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub#1210]
Currently, the doc directory contains documents and not code/usage documentation.
* Rename the doc directory to documents
* Create a new doc directory for documentation
* Put the relevant documentation (e.g. deployment) from the wiki into markdown files in the new doc directory
* Put links to those markdown files into the wiki. We want to have only one place to maintain the documentation.

**Comment by jelmd** [comment]
So doc/ contains no documents but documentation and documents/ contains documents but no documentation? Hmmm, interesting ...

**Comment by eugenk** [comment]
Exactly. As for rails standards, doc is supposed to be used for documentation of the app.
