### ISSUE TITLE
Error when trying to change an ontology on develop.ontohub

### ISSUE THREAD

**Issue by fabianneuhaus** [ontohub/ontohub#1232]
when I tried to commit a change to 
http://develop.ontohub.org/fabians-sandbox/CompetencyQuestion.dol
I got the error message below. 
(I edited the file via the web interface) 

Errno::ENOSPC in FilesController#update

No space left on device @ rb_sysopen - /tmp/repository_tempfile20150226-17206-uvdkof
Rails.root: /srv/http/ontohub/releases/20150216213406

Application Trace | Framework Trace | Full Trace
app/models/repository_file.rb:219:in `new'
app/models/repository_file.rb:219:in `prepare_opts_add_tempfile'
app/models/repository_file.rb:196:in `initialize_for_create_and_update'
app/models/repository_file.rb:52:in `initialize'
app/models/fake_record.rb:19:in `new'
app/models/fake_record.rb:19:in `create'
app/controllers/files_controller.rb:50:in `update'
Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"NomvsAR6f7UVjAdBOVrCzuH3xqoslA5o8iZblXZsHsU=",
 "content"=>"logic OWL\r\n\r\nontology my_ont = \r\n\tClass: Fish\r\n    Class: Human\r\n\t\tDisjointWith: Fish \r\n    Class: Woman\r\n\t\tSubClassOf: Human\r\nend\r\n\r\nontology CQ1 = my_ont then %% implies\r\n\tClass: Woman\r\n\t\tDisjointWith: Fish\r\nend\r\n\r\nontology Scenario = my_ont then \r\n\tIndividual: mary Types: Woman\t\r\nend\r\n\r\nontology CQ2 = Scenario then %% implies \r\n \tIndividual: mary Types: Human\r\nend\r\n ",
 "message"=>"removed implies",
 "repository_id"=>"fabians-sandbox",
 "path"=>"CompetencyQuestion.dol"}
Show session dump

Show env dump

Response

Headers:

None

**Comment by ebolloff** [comment]
This isn't relevant anymore.
