### ISSUE TITLE
Fix ontology delete

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub#1251]
Assume you have Ontology P with children C1, C2 in one file. If you want to delete the file or the ontology P, the current code fails because it would delete imported ontologies. In this case, we want to allow the deletion, though.

**Comment by eugenk** [comment]
I have a general question on ontology deletion, @tillmo. Currently, we only restrict deletion of an ontology S when there is another ontology T that imports S, i.e. if there is an `import` mapping. Do we want to restrict it only for `import` or for all kinds mappings (`view`, etc.)?

**Comment by tillmo** [comment]
It would be useful to also restrict this for views, because otherwise the view would become invalid.

**Comment by eugenk** [comment]
Okay, how about `alignment`, `hiding`, `minimization`, `cofree`, `free`?
I assume it's the same for these.

**Comment by tillmo** [comment]
yes, for every kind of mapping.
