### ISSUE TITLE
Ontology graphs view is broken

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub#1253]
Commit db8aaeeeb3b24f487a5d02c60d18e96e55f6ba85 breaks the graphs view on e.g. http://ontohub.dev/default/partial_order///graphs

An asynchronous request with `Content-Type:text/plain; charset=utf-8` goes to http://ontohub.dev/default/partial_order///graphs?_=1426063907897
and the response is:
```
ActionController::RoutingError at /default/partial_order/graphs
===============================================================

> uninitialized constant Api::V1::GraphsController
```

@0robustus1: I assigned this issue to you because I think you can fix this in less than a minute. If you say this is not your part, reassign it to me.

**Comment by 0robustus1** [comment]
Hotfixed this with cb6b5726c3232cac9a61044a8f8c87deb5c30314

**Comment by eugenk** [comment]
:+1:
