### ISSUE TITLE
Add sensible serializer for theorem

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub#1256]
In #1188, a basic TheoremSerializer is added. It has the same functionality as SentenceSerializer. Improve it by adding information on the proof attempts etc.

##### New tasks (edit)
* [x] Add serializers listed below.
* [x] Add API controllers to serve those contents

**Comment by 0robustus1** [comment]
@eugenk, talk to me about what you think would be sensible here (i'll need to write a schema for this).

**Comment by eugenk** [comment]
* theorem
  * proof status (identifier, reference to it)
  * references to proof attempts
* proof attempt
  * proof status
  * the three axiom lists
  * prover name
  * prover output (maybe reference to it)
  * time taken
  * attempt number
  * tactic script

**Comment by eugenk** [comment]
I think we agreed on those serializers:
* theorem
  * proof status
    * identifier
    * name
  * reference to proof attempts index
* proof attempt
  * reference to proof attempt configuration
  * proof status
    * identifier
    * name
  * reference to used axioms index
  * reference to used theorems index
  * reference to generated axioms index
  * prover
  * reference to prover output
  * time taken (in seconds)
  * attempt number
  * tactic script
* proof attempt configuration
  * reference to selected axioms index
  * reference to selected theorems index
  * selected prover
  * selected logic mapping
  * selected timeout

@0robustus1, can you comment on this, please?

**Comment by eugenk** [comment]
I just edited the previous comment to add:
* theorem
  * iri
  * name
  * text
  * state
* proof attempt
  * iri
  * state
* proof attempt configuration
  * iri

**Comment by 0robustus1** [comment]
Ok i've created the schemata for these model-resources:

- **Theorem**: https://masterthesis.rightsrestricted.com/ontohub/theorem.json
- **Proof Status**: https://masterthesis.rightsrestricted.com/ontohub/proof_status.json
- **Proof Attempt**: https://masterthesis.rightsrestricted.com/ontohub/proof_attempt.json
- **Proof Attempt Configuration**: https://masterthesis.rightsrestricted.com/ontohub/proof_attempt_configuration.json
- **Prover Output**: https://masterthesis.rightsrestricted.com/ontohub/prover_output.json

@eugenk please check the fields and the description.

**Comment by eugenk** [comment]
I think we should change the schema for the prover:

You have specified
```json
    "prover": {
      "description": "The name of the prover",
      "type": "string"
    }
```
whereas a prover will get more than just a name attribute. It will also get a display-name (not sure if relevant for the API) and in the future, I think it will have a type (automatic/assisted e.g. as in SPASS vs Isabelle).

Currently, it only has a name, but I'm already working on the display-name.

**Comment by 0robustus1** [comment]
Ok we've decided to put a pin in `display_name` (particularly because of the missing benefit - at least currently) for now. Wrt. to `type`: that one is ok, but it will be specified when the time comes (probably for API-v2).

**Comment by eugenk** [comment]
* https://masterthesis.rightsrestricted.com/ontohub/prover_output.json says:
```json
    "content": {
      "description": "The actual prover output",
      "type": "integer"
    }
```
the type should be `string` instead of `integer` ;)

* https://masterthesis.rightsrestricted.com/ontohub/proof_attempt.json says:
```json
    "prover": {
      "description": "The name of the prover used during this attempt",
      "type": "string"
    }
```
I think we should use the name `used_prover` instead of `prover` to emphasize the difference to the `selected_prover` in the ProofAttemptConfiguration. What do you think?

* https://masterthesis.rightsrestricted.com/ontohub/proof_attempt.json says:
```json
    "state": {
      "description": "The current proof-state",
      "type": "boolean"
    }
```
The state here is the same as in OntologyVersion (pending, processing, etc), so this should have the type `string` and have the description `"The evaluation state of this proof attempt"`. Maybe we should rename the field to `evaluation_state`. What do you think?

* https://masterthesis.rightsrestricted.com/ontohub/references.json says:
```json
    "proof_attempt_configuration": {
      "description": "Reference to a proof attempt configuration",
      "type": "object",
      "properties": {
        "iri": {
          "description": "The unique identifier of the proof attempt configuration",
          "type": "string",
          "format": "uri"
        }
      }
    }
```
Shall we include the number of the configuration in the json? We do it in proof attempts and ontology versions.

* https://masterthesis.rightsrestricted.com/ontohub/proof_status.json says:
```json
    "iri": {
      "description": "The unique identifier for the proof status",
      "type": "string",
      "format": "uri"
    }
```
How should an IRI of a proof status (e.g. `OPN`/`Open`) look like?

* https://masterthesis.rightsrestricted.com/ontohub/proof_attempt.json is missing a reference to the theorem.

* https://masterthesis.rightsrestricted.com/ontohub/proof_attempt.json is inconsistent in the naming of `number`:
```json
    "number": {
      "description": "The number of this proof attempt in relation to the theorem",
      "type": "integer"
    }
...
  "required": [
    "iri",
    "attempt_number",
    "state",
    "used_axioms",
    "used_theorems",
    "generated_axioms"
  ]
```

* I'd like to add the symbols and ontology to theorem (https://masterthesis.rightsrestricted.com/ontohub/theorem.json):
```json
    "ontology": {
      "$ref": "references.json#/definitions/ontology"
    },
    "symbols": {
      "description": "Reference to all symbols used in this sentence",
      "type": "string",
      "format": "uri"
    }
```

* https://masterthesis.rightsrestricted.com/ontohub/theorem.json calls the definition `definition` and https://masterthesis.rightsrestricted.com/ontohub/sentence.json calls it `text`. We should keep it consistent. Also why is `text` not required in sentence?

* While writing the first specs and the remaining serializers, I got:
```
JSON::Schema::SchemaError:
       The fragment '/definitions/logic_mapping' does not exist on schema https://masterthesis.rightsrestricted.com/ontohub/references.json#
```

**Comment by 0robustus1** [comment]
Ok i fixed basically everything you regarded as errors. As for the rest:

- `JSON::Schema::SchemaError` i hadn't defined logic-mapping yet. I will do so later today.
- `definition` vs. `text`: `definition` wins, i just hadn't changed it in sentence yet.
- `number` in proof_attempt_configuration-reference  
  If i remember correctly there is only one proof_attempt_configuration per proof_attempt, so the iri would not contain the number as part of the identifier, that why i left it out.
- `used_prover`: done
- `ontology` and `symbols` references in theorem: done
- proof-status-uri: i haven't made up my mind yet, but i assume it will somehow be based on the symbol-structure in the SZS ontology.

**Comment by eugenk** [comment]
> If i remember correctly there is only one proof_attempt_configuration per proof_attempt, so the iri would not contain the number as part of the identifier, that why i left it out.

How do you want to identify a ProofAttemptConfiguration if not by number/id? ProofAttemptConfigurations are shared between many ProofAttempts.

**Comment by eugenk** [comment]
We decided to leave the number out and have many urls to the same resource.

Now https://masterthesis.rightsrestricted.com/ontohub/proof_attempt.json says:
```json
    "theorem": {
      "$ref": "https://masterthesis.rightsrestricted.com/ontohub/theorem.json#"
    }
```
while it should be
```
    "theorem": {
      "$ref": "https://masterthesis.rightsrestricted.com/ontohub/references.json#/definitions/theorem"
    }
```
(I think).

Also `state` being boolean on proof_attempt is fixed (the type, not the description), but it is the same with theorem. I haven't noticed this before, sorry.
