### ISSUE TITLE
Indefinitely pending ontology on develop.ontohub.org

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1277]
http://develop.ontohub.org/repositories/sandbox/ontologies/912/versions

**Comment by tillmo** [comment]
should be sovled by #1557

**Comment by phyrog** [comment]
Is this still an issue, or can we close this?

**Comment by tillmo** [comment]
the problem is sitll there, see https://develop.ontohub.org/sandbox/horn

**Comment by tillmo** [comment]
duplicate, see #1729
