### ISSUE TITLE
Adapt proof status according to axiom selection

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1341]
This is a follow-up to #1135. If not all axioms have been selected, the proof status must be transformed before entering it into the database. Before implementing the issue, the transformation should be defined and theoretically justified. For example, NOC must be mapped to OPN, because we do not know whether the goal is a consequence of Ax just because it is not a consequence of some proper subset of Ax.

**Comment by eugenk** [comment]
I'm not really satisfied with using `OPN`. `OPN`/open means "A success value has never been established", i.e. a proof attempt has never been made. 

I can't find a fitting ProofStatus in the SZS ontology. Only selecting a subset of the axioms most certainly wasn't considered when designing the SZS ontology.

I suggest we add another ProofStatus to it:
`ACSA`, "AssumedCounterSatsifiable" with the following description:
> Countersatifiability is assumed, but not proven.
Let SAx be the selected subset of Ax, SF = SAx + {C}.
Some interpretations are models of the selected subset of SAx, and
some models of SAx are models of ~C.
- SF is not valid, ~SF is satisfiable, and C is not a theorem of SAx.
- Possible dataforms are Models of SAx | ~C.

The same way, we could define `ANOC`, "AssumedNoConsequence" with the description
> NoConsequence is assumed, but not proven.
Let SAx be the selected subset of Ax, SF = SAx + {C}.
Some interpretations are models of SAx,
some models of SAx are models of C, and
some models of SAx are models of ~C.
- SF is not valid, SF is satisfiable, ~SF is not valid, ~SF is satisfiable, and
C is not a theorem of SAx.
- Possible dataforms are pairs of models, one Model of SAx | C and one Model
of SAx | ~C.

Then, whenever a prover returns with `CSA` or `NOC`, we transform it to `ACSA` or `ANOC`.
