### ISSUE TITLE
ontologies are "pending" too long

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1353]
A newly uploaded ontology remains "pending" for approx. 3 mins, althoug there is not much load on the server and no other sidekiq jobs are being processed.

**Comment by tillmo** [comment]
possibly #1255 will solves this

**Comment by tillmo** [comment]
#1255 has not solved the problem.

**Comment by tillmo** [comment]
hopefully, #1452 will solve it.

**Comment by tillmo** [comment]
What about the following from http://www.sitepoint.com/comparing-background-processing-libraries-sidekiq/:

"Since Sidekiq uses threads, you can only uses libraries in Sidekiq if they are thread safe – anything else will likely cause a ton of problems that are difficult to track down. This really limits what you can do with Sidekiq.

Secondly, you must ensure that your code is thread safe (e.g. global variables are a no-go). Ruby (rather, the “default” ruby interpreter which is MRI) also has something called an “interpreter lock”, which means that only one thread can run at a time, so Sidekiq will work much better with alternative implementations of Ruby, such as Rubinus and JRuby."

**Comment by eugenk** [comment]
Just now #1452 was deployed to staging. Hopefully it's getting better.

**Comment by tillmo** [comment]
No, it is not getting better: @eugenk has re-scheduled all 45 pending ontologies this morning. 44 are still pending, see https://ontohub.org/admin/status

**Comment by tillmo** [comment]
should be solved by #1557

**Comment by phyrog** [comment]
Has this been resolved?

**Comment by tillmo** [comment]
works now
