### ISSUE TITLE
cannot confirm email

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1356]
neither on http://staging.ontohub.org nor on http://td.iws.cs.ovgu.de I can confirm my email. More precisely, when pressing the button for sending a confirmation email, nothing happens. Is this a configuration issue, or some ontohub issue?

**Comment by eugenk** [comment]
At least on develop.ontohub.org the email arrived a few hours after registration for me. And it had a wrong confirmation link (see #1345).

**Comment by eugenk** [comment]
this works
