### ISSUE TITLE
Cloning of private repositories is possible

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub#1383]
It is possible to clone a private repository via the git daemon. This should be restricted. I suggest, we only allow to clone private repositories via git-ssh.

**Comment by tillmo** [comment]
Why do we need the git daemon at all? Probably as a convenience for those users who have not registered and thus have not entered an ssh key?

**Comment by eugenk** [comment]
I think that's exactly the reason. It allows visitors to browse repositories locally, e.g. if
* they aren't sure whether to register or not 
* they just want to get hands on a repository quickly
* they use a computer other than their own (e.g. a lab computer) and only need read access

It could be interesting for teaching/classes as well (although I don't know which repositories might be of interest at this point).

**Comment by tillmo** [comment]
Maybe then we should change the message 

"You can clone the repository with git (read-only) or ssh-git (read-write)."

into

"You can clone the repository with git (read-only) or ssh-git (read-write, ssh-key required)."

and link the work "ssh-key" to the appropriate sub-menu of the settings menu.
