### ISSUE TITLE
Check if current Elasticsearch version works with Ontohub

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub#1397]
We are using elasticsearch 1.4.x right now. Check if version 1.7.x works with ontohub (or 1.5.x or 1.6.x if 1.7.x doesn't) and update the productive deployment documentation.

**Comment by ebolloff** [comment]
I updated ElasticSearch a few months ago on develop
```
wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.7.1.deb
+ dpkg -i elasticsearch-1.7.1.deb
```
 
When I try to start ElasticSearch
```
+ service elasticsearch start
 * Starting Elasticsearch Server
chown: invalid user: ‘elasticsearch:elasticsearch’
```

That's because there's a convention, that user names can have max. 8 letters. So our ES user is `esearch` and not `elasticsearch`.
@jelmd , @tillmo said that you did some replacements to fix this. Could you fix this on all machines? The current version is 1.7.3 afaik.

**Comment by jelmd** [comment]
Can you check your e-mail from 2015-08-31, plz? You should have got an e-mail, where I explained in detail the fix to use. Summary is:
```
+ dpkg --unpack /data/web/httpd/${HOST}.*/tmp/elasticsearch-4.5.6.deb
+ sed -r -e '/^#?ES_(USER|GROUP)=/ { s,^#,, ; s,=.*,=esearch, }'  -i /etc/default/elasticsearch.dpkg-new
+ sed -e '/rmdir/ s,$, || true,' -i /var/lib/dpkg/info/elasticsearch.postrm
+ dpkg --configure elasticsearch
+ update-rc.d elasticsearch defaults 95 10
```
The 2nd `sed ...` is to fix the bogus post remove script - not sure, whether it is still bogus in more recent versions.

**Comment by ebolloff** [comment]
```
+ service elasticsearch start
 * Starting Elasticsearch Server
sysctl: setting key "vm.max_map_count": Read-only file system
```

So it's updated and running with version 1.7.3. This error appears when starting it but @jelmd said, we should ignore it for now.

I'll adjust the documentation. Should I update it on other machines, too?

**Comment by jelmd** [comment]
Nice!

Wrt. the error: ignore it forever! A zone alias container is not allowed to modify this kernel parameter, since this is a global setting which would affect all zones ...

**Comment by ebolloff** [comment]
Updated and running on develop, test and staging (1.7.3)

**Comment by ebolloff** [comment]
I'll try version 2.0 on develop.

**Comment by ebolloff** [comment]
ES 2.0.0 runs on develop, test, staging.

**Comment by ebolloff** [comment]
ES 2.0.0 runs on ta, too.
