### ISSUE TITLE
Add secret_token yml-key to settings

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub#1398]
@jelmd wants the `secret_token` to be in the yml files so that he needs to touch fewer files for the configuration. I don't see a problem in putting the `secret_token` into the `config/settings.local.yml` as long as this file is not publicly available, but maybe I didn't think of everything.

I suggest to put something like this into the `settings.yml`:
```yml
# Your secret key for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!
# Make sure the secret is at least 64 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
secret_token: # nil - specify this key in the settings.local.yml and keep it secret
```
And this in the `config/initializers/secret_token.rb`:
```ruby
Ontohub::Application.config.secret_token = Settings.secret_token
```

Next, I'm not sure, if maybe the `config/secrets.yml` is the right place for it, but that would not reduce the number of config files that need to be touched...

@SGraef, @ebolloff, @tillmo (and maybe @0robustus1 if you still have time for a comment), what are your thoughts on this?

**Comment by tillmo** [comment]
`settings.local.yml` sounds like a good place for it (although I am not a security expert...)
