### ISSUE TITLE
redesign seeds to be able to use it in production environment

### ISSUE THREAD

**Issue by SGraef** [ontohub/ontohub#1448]
to be able to use the seeds on test.ontohub.org and develop.ontohub.org we have to change the beaviour of the seeds in production environment.

**Comment by eugenk** [comment]
Oh sorry, I didn't see that you have assigned yourself. I added some commits for this in the branch 1448-redesign_seeds_to_be_able_to_use_it_in_production_environment. I think this should be done, so I will create a pull request. Sorry again for hijacking your issue.
