### ISSUE TITLE
Ontohub tries to parse my CLIF ontology as DOL ontology (and fails, obviously)

### ISSUE THREAD

**Issue by fabianneuhaus** [ontohub/ontohub#1454]
The following file parses fine with Hets:
/imageschemafamily/path/movementAlongPath.clif
The error message 
https://ontohub.org/imageschemafamily/path/movementAlongPath///ontology_versions
shows that it tries to parse a DOL library. 
 
It seems that all of the CLIF ontologies that I have uploaded recently are affected by this bug.

**Comment by eugenk** [comment]
See https://github.com/spechub/Hets/issues/1516

**Comment by tillmo** [comment]
fixed by https://github.com/spechub/Hets/pull/1517
