### ISSUE TITLE
setup server farm with Hets instances

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1479]
this is needed for #1094 and #1355 and #1476

**Comment by tillmo** [comment]
the servers are (all xxx.iws.cs.ovgu.de)
riga,sofia,wien,prag,berlin,paris,rom,madrid,jack,sam,ro,laforge,picard,barclay,crusher,troi,riker,yar,worf,liz

**Comment by tillmo** [comment]
@jelmd: could you please start the hets servers on these machines and make their port 8000 accessible from ontohub.org?

**Comment by jelmd** [comment]
Yes, they are all running on the privileged port 800 to not interfere with stuff from normal users (which can use any port >= 1024). ta..td FWs got corresponding peep holes.

I gave all theo members the 'hets-workers' profile. So if something goes wrong/is suspicious they can login on the machine in question and start/stop/restart the hets-server using
```
svcadm {enable|disable|restart} hets:default
```
respectively. For more information see `/lib/svc/manifest/network/hets.xml`, svcadm(1M), pp..

**Comment by eugenk** [comment]
I created HetsInstance objects on ontohub.org which use those Hets servers by adding them to the `config/settings.local.yml` and executing 
```
RAILS_ENV=production bundle exec rake hets:recreate_hets_instances
```

However, three of them are not reachable: prag, barclay, riker

**Comment by jelmd** [comment]
Yepp, be prepared for such situatuions! These are Lab machines and some studs/windows users think, they need to switch it off, when they've done their work ...

**Comment by tillmo** [comment]
We started a first test of the server farm. We ran into the problem that ontohub.org has only 1GB for /tmp. We need at least 20GB.

**Comment by tillmo** [comment]
/tmp is a ram disk. Now /var/tmp is used, with 4TB.

**Comment by tillmo** [comment]
@SGraef, now that the disk problem has been fixed, could you please have a look at our experiment?

**Comment by tillmo** [comment]
Sidekiq has 0 busy working. It seems that nothing is being analysed at all, although there are hundreds of jobs in the pipeline. Newly submitted ontologies are not analysed either.

**Comment by eugenk** [comment]
This is set up and running.
