### ISSUE TITLE
new certificates for ontohub server

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1481]
they should be recognized by standard software and browsers

**Comment by SGraef** [comment]
we have right now the problem that firefox don't allow to open on ontohub. the message i get is:
"he certificate is not trusted because the issuer certificate is unknown. The server might not be sending the appropriate intermediate certificates. An additional root certificate may need to be imported."

**Comment by jelmd** [comment]
can you give the full URL, when this happens?

**Comment by SGraef** [comment]
https://ontohub.org

**Comment by jelmd** [comment]
Hmmm, I've no problem neither with FF (ESR 31.6) nor with Chrome(46.0.*).

Is there a chance, that you've removed one or more of the required Authorities? You should have:
Deutsche Telekom:
- Deutsche Telekom Root CA 2
- DFN-Verein PCA Global - G01
DFN-Verein:
- Uni Magdeburg CA

Can you check via    'Preferences ... | Advanced ... | -> Certificates  <- | <View certificates>'  ?

**Comment by jelmd** [comment]
Bah, this github crap screwed the posting up. Here again:
```
Deutsche Telekom AG:
- Deutsche Telekom Root CA 2
- DFN-Verein PCA Global - G01
DFN-Verein:
- Uni Magdeburg CA

Preferences ... | Advanced ... | -> Certificates <- |  <View Certificates> | -> Authorities <-
```

**Comment by tillmo** [comment]
Are these authorities included by default in Firefox etc., or do you have to add them manually?

**Comment by jelmd** [comment]
Not sure, but I think, they are included by default.

**Comment by tillmo** [comment]
I just see that wget does not have them by default:
```
wget https://ontohub.org
--2015-11-16 08:26:10--  https://ontohub.org/
Auflösen des Hostnamen »ontohub.org (ontohub.org)«... 141.44.24.80
Verbindungsaufbau zu ontohub.org (ontohub.org)|141.44.24.80|:443... verbunden.
FEHLER: Kann das Zertifikat von »ontohub.org« nicht prüfen, ausgestellt von »»/C=DE/O=Otto-von-Guericke-Universitaet Magdeburg/CN=Uni Magdeburg CA/emailAddress=ca@uni-magdeburg.de««:.
  Die Authorität des Ausstellers des Zertifikates kann lokal nicht geprüft werden.
Verwenden Sie »--no-check-certificate«, um zu dem Server »ontohub.org« eine nicht gesicherte Verbindung aufzubauen.
```
We definitely need certificates where no manual change of the settings is necessary. Something like https://letsencrypt.org/

**Comment by jelmd** [comment]
Might be. Both apps use different cert stores. What FF version do you use (which OS version)?

**Comment by SGraef** [comment]
i use Firefox 42.0 on OSX 10.10.5

**Comment by jelmd** [comment]
Uhmm, try this:  https://www.ovgu.de/  and than try https://ontohub.org/ again.  =8-|

**Comment by SGraef** [comment]
now it works again

**Comment by jelmd** [comment]
Yepp, FF adds them in the background =8-( ...

**Comment by ebolloff** [comment]
With the hop over https://www.ovgu.de/ it works at my machine, too.

**Comment by tillmo** [comment]
but wget still does not work!

**Comment by tillmo** [comment]
wget and curl work now. Good! The only thing that remains to be done is an automatic redirection from http to https. I am not sure where this should be done.

**Comment by eugenk** [comment]
Redirection from http to https has been done in #1613. Can this be closed now?

**Comment by tillmo** [comment]
yes
