### ISSUE TITLE
Files in public directory are not accessible

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub#1490]
If, for example, we try to access https://ontohub.org/robots.txt, rails doesn't find a route for this URL.
I think this happens because the `*path` route at the end of the routes.rb calls the IRIRouterConstraint which doesn't find an IRI.

**Comment by tillmo** [comment]
The fix #1493 has been deployed to ontohub.org, but robots.txt still leads to a 404. 
Note that something went wrong with the deployment, see #1495. However, this cannot be the cause of the 404.

**Comment by SGraef** [comment]
i have implemented an dirty-fix directly on ontohub.org we should investigate this more but the robots.txt is available now

**Comment by SGraef** [comment]
i found out that puma does not help to serve the public directory like passenger does so we have to configure rails the way that it does this. the pull request #1500 should fix this.

**Comment by SGraef** [comment]
in order to #1501 this issue can be closed
