### ISSUE TITLE
Ontohub practically down

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1492]
Today (Oct 13), there has been only one request that has been answered successfully (200). The rest has been (apart from redirects) always a 502 error.

**Comment by SGraef** [comment]
thats seems to be the same error we encounter in the meeting yesterday which is crawling all postgresql threads and so nobody can get data

**Comment by tillmo** [comment]
a first solution would be to install a robots.txt that forbids crawling.

**Comment by SGraef** [comment]
yeah that was our idea yesterday an we have to fix the routes that the robots.txt is reachable

**Comment by tillmo** [comment]
The problem started (in less severe extent) on October 5. On October 3, crawler requests reached a peak. Could this be a cause?

**Comment by SGraef** [comment]
maybe this could be the reason i have made commits in the corresspoding branch of #1490, if the tests are green this could be a fix for it

**Comment by SGraef** [comment]
when it does it is a fast fix and we should investigate more, but in order to make ontohub accessible, i think we should merge it as fast as possible and fix other afterwords. Or how do you think @tillmo?

**Comment by tillmo** [comment]
agreed

**Comment by eugenk** [comment]
I just merged #1493, published and deployed a new release and restarted the services on ontohub.org. Hopefully, it gets better. I have no time left to work on it *today*, though.
