### ISSUE TITLE
Problems with search

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1498]
@fabianneuhaus, please specify the problems

**Comment by ebolloff** [comment]
If you search for `blood` in our search, there are no results. If you search on bioportal, there are three results. So the search for terms is buggy.

**Comment by tillmo** [comment]
note that not all Bioportal ontologies have been mirrored to Ontohub, only those ones that are not too large

**Comment by ebolloff** [comment]
This should be fixed. There were only ~1500 Ontologies indexed, although we have ~4500 Ontologies on `ta`.
