### ISSUE TITLE
cannot clone with git

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1515]
```
git clone git://ontohub.org/dol-examples.git
Nach »dol-examples« wird geklont
fatal: unable to connect to ontohub.org:
ontohub.org[0: 141.44.24.80]: errno=Verbindungsaufbau abgelehnt
```

**Comment by tillmo** [comment]
it seems that this error occurred since @jelmd has changed the Apache config.

**Comment by jelmd** [comment]
Strange - the git service was not running anymore. Actually upstart manages the service and even if it dies, upstart should restart it. Hmmm ... Anyway, just in case: '+ service git-serv start' fixed it.

**Comment by tillmo** [comment]
thanks. I think that we should monitor such things, in order to avoid that Ontohub features fail to work without us noticing it.

**Comment by tillmo** [comment]
works now. Monitoring will by done by eye.
