### ISSUE TITLE
Broken Hets on develop.ontohub.org

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub#1559]
```
ontohub@tc:~$ curl "http://localhost:8000/dg/http%3A%2F%2Fdevelop.ontohub.org%2Fref%2F1%2Fhets-lib%2FPropositional%2FSatlib%2FBlocksworld%2FAnomaly%2F%2Fanomaly/just-structured?input-type=het;"
this query does not comply with RESTful interface: dg/http%3A%2F%2Fdevelop.ontohub.org%2Fref%2F1%2Fhets-lib%2FPropositional%2FSatlib%2FBlocksworld%2FAnomaly%2F%2Fanomaly/just-structured

ontohub@tc:~$ curl localhost:8000/version
v0.99, 1443428993
```
When I execute this on my development machine, everything is fine:
```
 ❯ curl "http://localhost:8000/dg/http%3A%2F%2Fdevelop.ontohub.org%2Fref%2F1%2Fhets-lib%2FPropositional%2FSatlib%2FBlocksworld%2FAnomaly%2F%2Fanomaly/just-structured?input-type=het;"
<?xml version='1.0' ?>
<DGraph filename="http://develop.ontohub.org/ref/1/hets-lib/Propositional/Satlib/Blocksworld/Anomaly//anomaly" mime-type="text/het" libname="anomaly" dgnodes="1" dgedges="0" nextlinkid="0">
  <DGNode name="anomaly" range="http://develop.ontohub.org/ref/1/hets-lib/Propositional/Satlib/Blocksworld/Anomaly//anomaly:3.1-270.3" reference="false" logic="Propositional" refname="anomaly" relxpath="/" />
</DGraph>

 ❯ curl localhost:8000/version
v0.99, 1450372295
```
@jelmd: Do you know what's wrong there?

**Comment by eugenk** [comment]
The same seems to be going on with the machine `jack`.

**Comment by jelmd** [comment]
Nope, don't know. localhost:8000 implies direct talk to the hets server, so it is a question for the hets experts.

**Comment by jelmd** [comment]
Wrt. jack et. al.: all lab machines incl. jack run the same binary (and usually the same OS revision), so the behavior/results should be the same for all of them. However timings might be different dueto other services/jobs running on them.

**Comment by tillmo** [comment]
on my local machine, I get the same error. I have `version of hets: v0.99, 1452189354`
@eugenk, could you try it with the same version (i.e. head of branch master)?

**Comment by tillmo** [comment]
Aha, with hets (instead of hets-server), I get the correct output. So the problem seems to be one of hets-server. Normally, hets-server should behave in the same way as hets, except that the GUI functionality is not supported.

**Comment by eugenk** [comment]
Alright, I reported it in https://github.com/spechub/Hets/issues/1557

**Comment by tillmo** [comment]
spechub/Hets#1557 is closed now, and I have updated Hets on develop.ontohub.org. Please check.

**Comment by eugenk** [comment]
It works fine on develop.ontohub.org.

**Comment by eugenk** [comment]
Could you update the version on ontohub.org as well?
After restarting `ontohub-god`, it should work on this machine, too.

**Comment by tillmo** [comment]
OK, done

**Comment by eugenk** [comment]
Okay, then this is done. Thank you!
