### ISSUE TITLE
Make OWL API work with Ontohub URLs that have no filename extension

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1578]
For Ontohub URLs without filename extension, e.g. `http://ontohub.org/sandbox/inconsistent`, we correctly deliver the raw text if the accept header is set correctly, e.g.
```
wget --header "Accept: text/plain" http://ontohub.org/sandbox/inconsistent
```
However, the OWL API appearantly does not set the accept header in this way. As a consequence, Ontohub delivers html, and the OWL API throws a syntax error. You can observe this behaviour e.g. if you enter `http://ontohub.org/sandbox/inconsistent` into Protégé (menu: open ontology from URL).

**Comment by eugenk** [comment]
The browser should send `text/html`. If no accept header is set, we should default to `text/plain`

**Comment by tillmo** [comment]
will possibly be fixed by #1658, so wait for that first.

**Comment by phyrog** [comment]
I believe this is a nofix like #1699? The new version of Protege (and the OWL API) does not seem to have this problem.

**Comment by tillmo** [comment]
yes, we should refer users to the latest version of Protégé and OWL API.

**Comment by phyrog** [comment]
I think my earlier comment was too hasty and we should re-open this issue. I just tried importing an ontology in Protege, and it does not throw an error, but it just fails silently and nothing is imported (which makes sense, how should Protege or the OWL API know how to parse our HTML).

What the new OWL API and Protege did fix, was the redirects, which did not work before; this case is something different entirely.

**Comment by phyrog** [comment]
@0robustus1 Would this work when the `Accept` header is not present?

```
reroute_on_header(header: 'Accept', value: '', to: ...)
```

**Comment by 0robustus1** [comment]
Well it shouldn't fail if you are talking about that. But empty string won't match for non-existence of header. So it won't have the same semantic as `present?`. (see https://github.com/0robustus1/specroutes/blob/60e0b10eda4ede044e06af403eb494a994d1df95/lib/specroutes/constraints/header_constraint.rb#L19-L21 for more info).

**Comment by 0robustus1** [comment]
But we can change the behaviour in specroutes if you think something else is more feasible. Just ping me again with the wanted change, and we can do it ;)

**Comment by phyrog** [comment]
Found another (easier) way around this by switching the `accept`s and the `reroutes`, which seems to work fine. Thanks nonetheless.
