### ISSUE TITLE
ontologies not displayed

### ISSUE THREAD

**Issue by mcodescu** [ontohub/ontohub#1586]
In Bioportal, when clicking on e.g. SNPO (http://ontohub.org/bioportal/SNPO) or SO (http://ontohub.org/bioportal/SO), I get "We're sorry, but something went wrong.". The ontologies from Bioportal should be reanalyzed anyways, but there used to be no problems in this repository, so maybe something is indeed wrong with Ontohub

**Comment by eugenk** [comment]
I changed the code (like in the pull request) directly on the machine ontohub.org and restarted puma. Then I rolled back the changes, but didn't restart puma. This way, the changes are still loaded and the bug seems fixed, but the next deployment won't make problems because of changes files.
