### ISSUE TITLE
Add a sidekiq queue for migrations

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub#1602]
If we process huge jobs like in #1476, all ontohub parsing capacities are used for a very long time. This makes ontohub parsing unusable. Introduce a new queue just for such huge jobs which uses all available hets instances but one (or two). This also requires that (temporarily if possible) the `hets` queue only uses one (or two) instances.

**Comment by eugenk** [comment]
First I want to say that if I talk about "migrations" here, I mean huge data migrating tasks like #1476, not Rails migrations.

Instead of using some hets instances only for migrations (which then are "disabled" whenever we don't migrate), we could add a queue `hets-migration` which is prioritised lower ([using weights](https://github.com/mperham/sidekiq/wiki/Advanced-Options#queues)) than the queue `hets`. If the queue `hets` has a weight of 5 and `hets-migrate` has a weight of 1, then Sidekiq's polling mechanism checks `hets` for new jobs 5 times as often as `hets-migrate`. Then, all hets instance are shared between these two queues.

**Comment by tillmo** [comment]
OK, but what happens if there are 1000 migration jobs and 1 job submitted interactively by a user? Could it still be that 200 migration jobs have to be processed before it's the turn of the user's job?

**Comment by eugenk** [comment]
As far as i understand the sidekiq documentation, this can't be.

A sidekiq worker process polls the redis database for new jobs in the queues. These queues are checked in the user-defined order, for example `priority_push`, `hets`, `hets-migrate`. Apart from that, one can additionally define how often a queue is checked for new jobs (relative to the other queues).

If there are 0 jobs in the `priority_push` queue, 1 in the `hets` queue and 1000 in the `hets-migrate` queue, then the first job that is processed the one from the hets queue.

If there are only 1000 jobs in the `hets-migrate` queue and right after all the worker threads start processing a job a new job is enqueued in `hets`, then this job should be scheduled next.

**Comment by tillmo** [comment]
OK, sounds good.
