### ISSUE TITLE
Offline HetsInstances get chosen and raise errors

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub#1610]
If the machine running a HetsInstance is offline and this instance gets chosen, an error is raised:
```
Errno::EHOSTUNREACH: No route to host - connect(2) for "madrid" port 800
```
The same instance gets chosen again and again. It must be marked as offline and another instance must be chosen.

**Comment by tillmo** [comment]
first write some documentation about the interaction between Ontohub and Hets, see #1643

**Comment by tillmo** [comment]
the problem with this issue is to set the 'up' flag to 'false'. This is not possible without changing some validations or hooks.

**Comment by eugenk** [comment]
If there is no online hets instance, an error should be raised and the users should be notified that they can try it again. We could also schedule a retry job to run in an hour (`SomeWorker.perform_in(1.hour)`.
