### ISSUE TITLE
static analysis of extract

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1616]
We need this urgently for the OMG meeitng next week.
@mcodescu, could you just implement a trivial module extraction that always delivers the whole theory of the original OMS/DG node as module? The DG should be extended by a node for the module with an inclusion theorem link into the original node (similarly to intersections). Also, the original node must be flattenable.
I will in parallel take care of a method for module extraction.

**Comment by mcodescu** [comment]
I think this should be a Hets issue. I have implemented something on a new branch of Hets, but I can't parse ```O extract A```, where A is a class of O.

**Comment by tillmo** [comment]
sorry, your are right. I have moved this to https://github.com/spechub/Hets/issues/1587
