### ISSUE TITLE
Fix contradictory code in team_users

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub#1626]
in [app/models/team_user.rb:17-21](https://github.com/ontohub/ontohub/blob/5d213a05436c75038479e0bcc0bcdf87e2005a05/app/models/team_user.rb#L17-L21) we have:

```ruby
  delegate :team_users, :to => :team

  def team_users
    self.class.where(:team_id => team_id)
  end
```

which makes two definitions for the same method name. Check which one is actually used and remove the other.

**Comment by phyrog** [comment]
The second one is used, but they do the same thing.

The first one essentially translates to `self.team.team_users`, which internally is of course nothing else than `TeamUser.where(:team_id => team_id)`.

Since the first one is a bit clearer (in my opinion) I would remove the second one.
