### ISSUE TITLE
hets is not found when using hets-server

### ISSUE THREAD

**Issue by phyrog** [ontohub/ontohub#1631]
Ontohub depends in several places (e.g. https://github.com/ontohub/ontohub/blob/staging/spec/support/fixtures_generation/base_generator.rb#L10) on an executable called `hets`, which does not exist when using `hets-server`.

**Comment by eugenk** [comment]
* settings_for_development.yml should be deleted (the hets path in `Settings.hets.executable_path` should be used; hets-lib is not needed any more)
* lib/tasks/hets.rake needs to be adjusted
