### ISSUE TITLE
Add edit button to versions list

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub#1633]
For failed ontologies like version 1 in http://ontohub.org/sandbox/syntax%20error/periods///ontology_versions, we want to have an edit button under the red error message box.

This edit button must only be shown if the failed version is the most recent version and if the user is allowed to edit the file. You can see the permission check at the edit button on file view (see the following link).

Clicking this button shall switch the page to the [file view](http://ontohub.org/sandbox/syntax%20error/periods.dol) and act as if the "Edit file" button was clicked on page load.

You can see the corresponding coffeescript of the file view/edit function in [app/assets/javascripts/codemirror-custom.js.coffee](https://github.com/ontohub/ontohub/blob/3aa9e3f744713c1a073dd004fbb77b04ac0b6e0c/app/assets/javascripts/codemirror-custom.js.coffee)
and the edit button in the file view in [app/views/files/show.html.haml:26](https://github.com/ontohub/ontohub/blob/3aa9e3f744713c1a073dd004fbb77b04ac0b6e0c/app/views/files/show.html.haml#L26)

**Comment by tillmo** [comment]
If the user has no permissions for editing, a "view" button could be displayed instead.

**Comment by phyrog** [comment]
Is the "view" button also just wanted for the most recent version? It might be as well on every version, since there already is a download button for every version.

To trigger the `enableEditing` I would use an anchor (`#edit` or similar); this is the easiest way that came to my mind, maybe one of you has a better idea?

**Comment by tillmo** [comment]
I think "view" should be provided for all versions.

**Comment by eugenk** [comment]
An anchor is a good idea.

If we would want to combine editing with other "on load" actions by URL, we should use something else, but I can't think of another reasonable javascript-action other then editing.
