### ISSUE TITLE
Sidekiq waits too long before performing jobs

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub#1642]
Sidekiq doesn't run new jobs for very long time. Maybe this will be fixed with #1618, but we are not sure.

**Comment by eugenk** [comment]
I suspect a deadlock caused by our parallel ontology parsing implementation. Might be solved with #1697, but needs further testing.

**Comment by eugenk** [comment]
in pause due to #1618 and #1697

**Comment by tillmo** [comment]
now that #1618 and #1697 have been merged: what is the status here?
Note that I need to demo at FOIS tomorrow. Currently, I cannot show the upload or editing of ontologies, because the analysis simple does not work.

**Comment by eugenk** [comment]
This is still an issue. I don't understand why this worked on develop.ontohub.org but not on ontohub.org. The fixes are deployed there. We need to investigate this further, but at this point, I have no idea what exactly is causing the problems.

Can you demo Ontohub with develop.ontohub.org?

**Comment by tillmo** [comment]
develop.ontohub.org exhibits the same problem, see https://develop.ontohub.org/sandbox/horn and #1277

**Comment by tillmo** [comment]
moreover, of course it would be much better to demo on ontohub.org, because the demo may lead to new users of Ontohub.

**Comment by tillmo** [comment]
in sidekiq-default.log, I found many occurrences of:
```
/local/usr/ruby/versions/2.1.10/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/spec_set.rb:94:in `block in materialize': Could not find multi_json-1.12.1 in any of the 
sources (Bundler::GemNotFound)
```
Moreove, 20 of 20 sidekiq workers are busy:
```
 2498 ontohub   20   0 4410428 323152  14996 S   0.3  0.1   5:54.12 sidekiq 3.5.4 webapp [1 of 5 busy]                                                                     + 
 2512 ontohub   20   0 5899492 361252  15088 S   0.3  0.1   3:52.68 sidekiq 3.5.4 webapp [20 of 20 busy]                                                                   + 
 2540 ontohub   20   0 3818224 319048  15112 S   0.3  0.1   6:00.17 sidekiq 3.5.4 webapp [0 of 1 busy]                                                                     + 
 4631 ontohub   20   0   16776   2940   2456 R   0.3  0.0   0:00.08 top                                
```

**Comment by tillmo** [comment]
could we delete all sidekiq jobs and start from scratch?
Is there a possibility to increase the sidekiq log level?

**Comment by tillmo** [comment]
OK, I have stopped the 20 hets workers. The effect is that the next 20 jobs are assigned to the 20 hets workers, but they still seem to be idle though busy. Some kind of deadlock?

**Comment by tillmo** [comment]
@eugenk, could you perhaps insert some tracing messages into the code and try it on develop.ontohub.org?
Perhaps also switch off the load balancer (aka heart beat)?

**Comment by eugenk** [comment]
Now I can get to debugging it. Sorry, I had a very long day with many appointments. Will do my best to fix this now.

**Comment by eugenk** [comment]
It's a deadlock that seems to be caused by the `choose_hets_instance` key. I inspected the redis database contents with the redis-command `keys *:semaphore:*`

As soon as I know more about it, I will post it here and try fixing it.

**Comment by tillmo** [comment]
good! I count on you...

**Comment by eugenk** [comment]
I think I found a problem in [lib/semaphore.rb](https://github.com/ontohub/ontohub/blob/e8ec59dda8f903e81cb5cceaef93d20a0812fc77/lib/semaphore.rb) involving the following lines:

* [Line 44](https://github.com/ontohub/ontohub/blob/e8ec59dda8f903e81cb5cceaef93d20a0812fc77/lib/semaphore.rb#L44) The entry point of the locking internals
* [Line 50](https://github.com/ontohub/ontohub/blob/e8ec59dda8f903e81cb5cceaef93d20a0812fc77/lib/semaphore.rb#L50) We need a mechanism `locked?` to check whether a mutex is locked. This is only possible with the steps in the `locked?` method.
* [Line 66](https://github.com/ontohub/ontohub/blob/e8ec59dda8f903e81cb5cceaef93d20a0812fc77/lib/semaphore.rb#L66) Our mutex is locked here. We need to do the locking itself in a critical path because most of the `locked?` method must be atomic. Hence, locking our mutex must be atomic as well.
* [Line 68](https://github.com/ontohub/ontohub/blob/e8ec59dda8f903e81cb5cceaef93d20a0812fc77/lib/semaphore.rb#L68) Our mutex is unlocked here; again, as an atomic operation.
* [Line 75](https://github.com/ontohub/ontohub/blob/e8ec59dda8f903e81cb5cceaef93d20a0812fc77/lib/semaphore.rb#L75) Making the above an atomic operation is done by using another mutex, which is retrieved here.
* [Line 88](https://github.com/ontohub/ontohub/blob/e8ec59dda8f903e81cb5cceaef93d20a0812fc77/lib/semaphore.rb#L88) This line shows that the same lock key `LOCK_ACTION_KEY` is used for making the locking, unlocking and `lock?` operations atomic.

And here is the problem: Since we use the same key for the critical paths of locking and unlocking, a deadlock is possible as in this scenario:

### Deadlock Scenario

* **A** has opened `LOCK_ACTION_KEY` to open `lock_key` at [line 66](https://github.com/ontohub/ontohub/blob/e8ec59dda8f903e81cb5cceaef93d20a0812fc77/lib/semaphore.rb#L66), but waits for `lock_key` to be free because of **B**.
* Part of **B**'s call stack is [line 68](https://github.com/ontohub/ontohub/blob/e8ec59dda8f903e81cb5cceaef93d20a0812fc77/lib/semaphore.rb#L68); [line 75](https://github.com/ontohub/ontohub/blob/e8ec59dda8f903e81cb5cceaef93d20a0812fc77/lib/semaphore.rb#L75), meaning it has done its work using `lock_key` and it wants to open `LOCK_ACTION_KEY` to unlock `lock_key`, but waits for `LOCK_ACTION_KEY` to be free because of **A**
* Both wait, no one can work

### Idea of a Solution

* We need the locking, unlocking and `locked?` to be atomic operations, because we need the `locked?` check to yield correct results during parsing.
* We should use two distinct locks for locking (`LOCKING_KEY`) and unlocking (`UNLOCKING_KEY`) instead of one `LOCK_ACTION_KEY`.
* We should make `locked?` a double-ciritical path, first locking with `LOCKING_KEY` and then locking with `UNLOCKING_KEY`, checking the state and then unlocking them again in the reverse order.
  * Scenario A
    * If **C** locked with `LOCKING_KEY`  inside `locked?` and **B** locked with `UNLOCKING_KEY`, then **C** waits for **B** to finish unlocking.
    * Then **A** wants to lock using `LOCKING_KEY` and waits for **C**.
    * Then the only option is for **B** to unlock, then **C** can lock using `UNLOCKING_KEY`.
    * **A** still waits. Assume, **D** wants to unlock using `UNLOCKING_KEY`, then **D** waits for **C**
    * **C** finishes its check, unlocks both, `LOCKING_KEY` and `UNLOCKING_KEY` so that **A** and **D** can continue.
    * No deadlock.
  * Scenario B
    * If **A** locked with `LOCKING_KEY` and **B** locked with `UNLOCKING_KEY` and **C** wants to use `locked?`, then **C** waits
    * As soon as both keys are freed by **A** and **B**, **C** can enter its critical path.
    * No Deadlock
* All three operations should finish very quickly and no long waiting for the `Semaphore`-internal locks should happen.

**Comment by eugenk** [comment]
The same thing will happen over and over again, even with these different keys. I implemented a hotfix for the case of "no imports from one file into many files" and deployed it on ontohub.org. However, this must be addressed properly in the future. It can't be fixed properly with the current state of the gem `redis-semaphore`. I think we need to implement a proper `locked?` method inside this gem and use it. However, I'm not sure how to do this.

**Comment by tillmo** [comment]
I think the general problem is that a semaphore without deadlocks simply cannot implement it in software only, because you get into an infinite regress: reading and then modifying the lock must be atomic, so you have to protect it using another lock. But  reading and then modifying that lock also must be atomic, so you have to protect it using yet another lock, etc.
Hence, a true semaphore has to be provided by the operating system in interaction with the micro processor hardware. 
Hopefully, Ruby's class Mutex is such a thing.

**Comment by eugenk** [comment]
Right, but unfortunately, Ruby's Mutex is not applicable here. We need a lock across multiple processes (e.g. puma and sidekiq) while Ruby's Mutex only can lock between the threads of a single process.

**Comment by tillmo** [comment]
I see. Maybe the problem is that you implement separate `lock` and `unlock` methods on top of the redis semaphore. I suggest to use the redis semaphore directly in the way described under "usage" at https://github.com/dv/redis-semaphore.

**Comment by eugenk** [comment]
Yes, it definitely is the problem. I did this because we *need* a `locked?* method that works across processes. And the one implemented in the gem does not. It doesn't even work if two instances `A` and `B` of `Redis::Semaphore` have the same key, then `A.lock` was called and then `B.locked?`. As stated in #1729, we need to adjust the gem.

**Comment by eugenk** [comment]
Closing because the origin of the issue is #1729.
