### ISSUE TITLE
restrict http to https redirection to login page

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1699]
The general redirection of http to https leads to problems with the OWL API, and thus also with Hets and Protégé. E.g. the ontology `http://ontohub.org/ref/17/meta/dol-ontology` cannot be parsed by Hets, nor loaded into Protégé. While https://github.com/spechub/Hets/issues/1620 solves the problem for Hets, we do not have our hands on Protégé and the OWL API. And they do not follow redirections that switch the protocol.

A solution could be to turn of the general http to https redirection done by Apache, and let Ontohub do this redirection, but only for pages where encrpytion is important, like login pages.

**Comment by phyrog** [comment]
Protege 5.0 seems to use a newer version of OWL API, [that does not have this bug anymore](https://github.com/protegeproject/protege/issues/17#issuecomment-28610859).
