### ISSUE TITLE
Pagination in repository history is broken

### ISSUE THREAD

**Issue by phyrog** [ontohub/ontohub#1706]
e.g. https://ontohub.org/repositories/sandbox/master/history

- The pagination only shows the current page
- The next button is always show, even when the user is at the and of the history

This can be confirmed on staging, develop and master.

**Comment by eugenk** [comment]
It's not feasible to change this. We would need to calculate the number of pages/commits by walking through all commits. There is, however, no way to simply query for the number of commits. Hence, we can't predict whether or not we actually need to display the next button. So, we show the button whenever we cannot be sure that there may or may not be more commits: The only case when we are sure that there are no more pages is if `n` entries per page are configured, but only `m` with `m < n` are displayed.

Showing only the current page has the same reason. We simply don't know whether or not there is the page with number `n+1`.

**Comment by phyrog** [comment]
OK, so the history should be changed to use the `Commit` model first, before this can be changed?
