### ISSUE TITLE
Not everything gets loaded in rails c

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub#1728]
Logged into the `rails c production` on ontohub.org, when I execute
```ruby
ActiveRecord::Base.logger.level = 1; threads = Repository.find_by_path('eugens-test-1').ontologies.where(parent_id: nil).map(&:current_version).map { |ov| Thread.new { ov.parse_full } }.each(&:join)
```
I get errors that indicate incomplete application loading. It randomly doesn't find classes in the top namespace, like `Semaphore`, `AccessTokenDeletionWorker` or `TimeoutWorker` (raising `NameError`s with `NameError: uninitialized constant ...`). As far as I remember, they all reside in the `lib` directory. I'm not 100% sure of it, though.

**Comment by eugenk** [comment]
This also seems to be a problem in Sidekiq.

**Comment by eugenk** [comment]
Maybe don't *auto*load the lib directory (lazily), but rather eager load it.

**Comment by phyrog** [comment]
The problem with eager loading `lib` is that there are some files that are only for command line git and should not be loaded normally. Unfortunately we can only specify directories to be eager loaded, but not files (where we could exclude those). For that to work, we need to split the `lib` directory into files that should be loaded and those that should not be loaded normally (`environment_light.rb` is one of those).

**Comment by eugenk** [comment]
So, now, this is related to #1597.

**Comment by tillmo** [comment]
This split should be not too difficult?

**Comment by phyrog** [comment]
I think [this](https://github.com/rails/rails/issues/15089) is the same problem we're having. The multiple threads are loading the same files at the same time, which is not thread-safe up until [Rails 4.2](https://github.com/rails/rails/commit/112077c255879351edf4530791cc4bcc7bd4005b).

We could try to monkey patch the changes in the commit (which is basically just a lock around the loading) into our rails.
