### ISSUE TITLE
Fix Deadlocks Caused by Semaphore 

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub#1729]
This is the successor of #1642. Jobs are not performed because of deadlocks that are caused by our Semaphore class. See https://github.com/ontohub/ontohub/issues/1642#issuecomment-231241099 for a description of the problem. The same problem occurs, for example, in [lib/hets/concurrent_evaluator.rb:39](https://github.com/ontohub/ontohub/blob/329a411da882f3d451b3257eea99c9262b4c3a68/lib/hets/concurrent_evaluator.rb#L39) if it is called multiple times in parallel.

A proper fix needs to change the gem [redis-semaphore](https://github.com/dv/redis-semaphore) in a way that `locked?` can be used across different processes (hence, on different semaphores on the same key). Instead of our complicated Semaphore class (which is complicated because of our implementation of `locked?`), we should only wrap the original redis-semaphore.

**Comment by tillmo** [comment]
still, some ontology is indefinitely pending:
https://develop.ontohub.org/sandbox/horn_new///ontology_versions

**Comment by eugenk** [comment]
Please try again. I can't reproduce it now.

The problem was that the services on develop.ontohub.org were not running because a branch was merged to develop that should not have been merged. This is fixed now.

**Comment by eugenk** [comment]
Oh and I restarted the jobs that were pending/processing in that ontology.

**Comment by tillmo** [comment]
on develop.ontohub.org, jobs are indefinitely pending:
https://develop.ontohub.org/ssh_test/Family///children

**Comment by eugenk** [comment]
The pending jobs don't seem to be a mutex problem but rather a problem that only occurs on develop.ontohub.org.
