### ISSUE TITLE
Finalise Jenkins configuration

### ISSUE THREAD

**Issue by eugenk** [ontohub/ontohub#1754]
There are still some things to do with Jenkins:

* [x] Start Hets on the configured port (see #1747)
* [x] Run nightly builds of staging
* [x] Send an email to the developer mailing list as soon as the staging build is red (for the first time since the last green test).

**Comment by jelmd** [comment]
a) see  	6057f66
b) no nightly builds: will be automagically done when the system gets an update
c) done

**Comment by eugenk** [comment]
Well, that's even better.
