### ISSUE TITLE
commited versions does not lead to new ontology version

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#1777]
see https://ontohub.org/essli_2016/Propositional/engine//Engine///ontology_versions
There is only one ontology version for commit fdf32bd4f. However, there is no ontology version for 9cf10ce. Instead, it seems that the existing version is used.

**Comment by eugenk** [comment]
Did you put this commit up there via git-push? It seems like there is a big problem with pushing, see #1779.

**Comment by tillmo** [comment]
yes. So probably it is just #1779.

**Comment by tillmo** [comment]
duplicate
