### ISSUE TITLE
Formalize ontology repository service in IDL 3.5

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#179]
There is a teleconference about discussing the programming interface of Ontohub, which should include the methods of BioPortal, of other web-based ontology repositories, of the OORService API. The advocated idea is to have a small number of parametrized and powerful methods such as "getOntology" so that the more specialized methods such as "getOntologyByName" can be implemented in terms of the former. The programming interface will be implemented in OMG IDL 3.5.

• An informal API, on which the IDL one must be based, can be found at http://tinyurl.com/onto-arch .
• Priority must be given to ontology services.
• Specialized methods must have a reference implementation using the general parametrized methods.
• The API should incorporate (some aspects of) the git API, involving repositories and branches

The API is specified int the directory api of the branch specifying179_formalize_ontology_repository_service.

SUGESTION:
There should be one single method for retrieval (of ontologies), with parameters for controlling what is retrieved and what is used as filter (e.g. symbols, axioms, metrics, categories, groups, versions, other metadata).

The parameters for controlling what is selected/filtered will have the form of the 'metadata' as a template (via XSLT or a similar translation). Each parameter in the metadata becomes a possible 'filter'.

**Comment by 0robustus1** [comment]
We use WADL and the [specroutes](https://github.com/0robustus1/specroutes) for formalizing the API.
