### ISSUE TITLE
Fix Errors in BasicProofs Definition

### ISSUE THREAD

**Issue by 0robustus1** [ontohub/ontohub#230]
The model `BasicProof` currently has a `belongs_to` relation to `:translation`.

This needs to be changed to `:logic_mapping`.

Furthermore a `BasicProof` `belongs_to` a `:sentence`.

Migrations must also be adjusted.

It is possible that Parsing is also not performed correctly (because
we should experience errors otherwise).

**Comment by eugenk** [comment]
Delete `BasicProof` because it is not used and we have other models for the whole proving pipeline.
