### ISSUE TITLE
Determine open proof obligations for ontologies

### ISSUE THREAD

**Issue by 0robustus1** [ontohub/ontohub#231]
After #230 is fixed/closed we need a method to determine open proof
obligations for a given ontology. This is especially needed for extension of
ontology-information in the graph representation (graphs#index).

This is defined as follows:

Every sentence of the ontology that isn't an axiom should be proven

If a sentence is referenced in BasicProofs it is proven

**Comment by eugenk** [comment]
I don't understand this part:
> If a sentence is referenced in BasicProofs it is proven

**Comment by eugenk** [comment]
@tillmo: This looks like it's not needed anymore. Can it be closed (after removing the empty `BasicProof` model)?

**Comment by eugenk** [comment]
This is not needed anymore.
