### ISSUE TITLE
Some misleading information in bulk upload interface

### ISSUE THREAD

**Issue by clange** [ontohub/ontohub#26]
First of all, the bulk upload interface (which I didn't use so far) is excellent!

Just some minor things that could be improved:

* I think that, here, success (the green "created" message) merely means that an ontology was successfully retrieved from its URL. Maybe not even that, as it happened to me that I quickly switched to the "ontologies" view, and the status was still "downloading". In any case one might get the false impression that _Hets_ succeeded on the ontology, which need not be the case.
* Here and elsewhere I would use a consistent terminology. The "create ontology" interface speaks of "URL to _import_ the ontology from", whereas it is "bulk _upload_". I tend to favor "import" – but you might object, as it might be confused with one ontology importing another ontology, i.e. with the link type "import" between two ontologies.
* It would be nice if the successfully retrieved ontologies in the "progress bar list" could directly be linked to their ontology pages, as I think the user would often like to go there in the next step. Same for some errors such as "URI has already been taken" (BTW "URI" should be in uppercase!)

**Comment by SGraef** [comment]
closed we dont have these interface anymore
