### ISSUE TITLE
http://omdoc.org/ontology# fails to import (404 not found)

### ISSUE THREAD

**Issue by clange** [ontohub/ontohub#27]
I have an ontology at http://omdoc.org/ontology#. When I import it into Ontohub using this URI=URL, it says "404 not found", whereas it can be downloaded from http://omdoc.org/ontology and then fails for a different reason (#28).

Even though the URL fragment is irrelevant for retrieval, it makes a difference wrt. linked data deployment (303 vs. no 303), so the right way to import this ontology is to use the hash.

Using or not using the hash should not make a difference to downloading. I tried it with wget and in both cases the result was the same: successful download of the ontology.

**Comment by SGraef** [comment]
it is implented
