### ISSUE TITLE
Setting URI on import is actually wrong

### ISSUE THREAD

**Issue by clange** [ontohub/ontohub#30]
"Create ontology" makes a URI mandatory. I know I requested this behavior, but actually I understood that it's wrong.

Many ontologies have their own URI declared inside; at least in OWL it's common practice, but it's even possible in Common Logic. When ontologies are published in linked data style (something on which we can't rely though, and which we don't know before having downloaded and processed the ontology), URL and URI coincide.

However, we will only find out the URI of an ontology by running Hets on it. [Hets does not yet tell us the URI though.](http://trac.informatik.uni-bremen.de:8080/hets/ticket/1016)

As we need to prepared for Hets to fail, or for an ontology not declaring its own URI (which is often the case in Common Logic, RDF, and most other logics), we should assign a reasonable default: the Ontohub URL. (This is reasonable in any case; see #24.)

This whole business requires the URI field to be removed from the "create ontology" dialog. Still we should be prepared for the user wanting to override the Ontohub-/Hets-assigned URI of an ontology; the current "edit ontology" dialog is sufficient for this.

#24

**Comment by tillmo** [comment]
we now have loc/ids
