### ISSUE TITLE
confirm ontohub registration

### ISSUE THREAD

**Issue by fabianneuhaus** [ontohub/ontohub#369]
I try to login and am asked to confirm my registration. However, I don't remember getting a confirmation email. Even if I got one and deleted it accidentally, I should be able to get a new one.

**Comment by tillmo** [comment]
actually, it does not work. When I press the button "Resend confirmation instructions" (on staging.ontohub.org), I do not get an email.

**Comment by eugenk** [comment]
Just tested it. The confirmation emails by registration and by resending-button are now delivered on both ontohub.org an develop.ontohub.org (staging.ontohub.org is down at the moment).
