### ISSUE TITLE
links between ontologies not shown properly

### ISSUE THREAD

**Issue by fabianneuhaus** [ontohub/ontohub#371]
See

http://develop.ontohub.org/repositories/common-logic-structural-ontology/ontologies/16609/graphs

injective.clif imports two  ontologies. This is not displayed.

**Comment by eugenk** [comment]
Do you have another example of this problem. The linked ontology id does not exist any more.

**Comment by ebolloff** [comment]
@fabianneuhaus could you give us another example?

**Comment by tillmo** [comment]
https://ontohub.org/colore-sample/algebra/module///mappings show a mapping that however is not displayed in the graph.

**Comment by tillmo** [comment]
better example:
here you see the mappings as they should be: https://ontohub.org/colore4/algebra/module///mappings
I created a fork of the repo, and here you do not see the mappings: https://develop.ontohub.org/colore5/algebra/module///mappings

**Comment by tillmo** [comment]
works now, see https://develop.ontohub.org/colore5/algebra/module///graphs
