### ISSUE TITLE
cannot delete repository

### ISSUE THREAD

**Issue by fabianneuhaus** [ontohub/ontohub#372]
I tried to delete a repository and got the following response:

NameError in RepositoriesController#destroy

uninitialized constant Ontology::Category
Rails.root: /srv/http/ontohub/releases/20131027194555

Application Trace | Framework Trace | Full Trace
Request

Parameters:

{"_method"=>"delete",
 "authenticity_token"=>"9ycg2nC56i5JZh14AxLu3C7JlmDyCplFpdSEdmq5FYk=",
 "id"=>"common-logic-structural-ontology"}
Show session dump

Show env dump

Response

Headers:

None

**Comment by eugenk** [comment]
This is not a problem any more. It works on the staging branch.
