### ISSUE TITLE
Fix symbol search

### ISSUE THREAD

**Issue by DanielCoutoVale** [ontohub/ontohub#374]
Searching for the symbol "Cat" crashes the server.

URL: http://develop.ontohub.org/entities_search?utf8=✓&q=Cat

![screen shot 2013-11-05 at 14 01 46](https://f.cloud.github.com/assets/1628721/1473435/9d9b75b6-461a-11e3-93b1-51c8a70102a1.png)

**Comment by eugenk** [comment]
We don't have a symbol search any more.
