### ISSUE TITLE
own environments for deploy pages?

### ISSUE THREAD

**Issue by 0robustus1** [ontohub/ontohub#376]
How about having own environments,
besides **development**, **test** and **production** for the deployment versions?

This is especially about *develop.ontohub.org* and *staging.ontohub.org*.

If we use specific environments, like **develop** and **staging**,
for these deployments it'll be much easier to manage
what is specific to those machines, and what should additionally be displayed,
e.g. the commit-id of the currently running version on *develop.ontohub.org*
and *staging.ontohub.org*. This is information which probably shouldn't
be displayed on *ontohub.org*.

**Comment by eugenk** [comment]
The essence of this is implemented with our settings.local.yml
