### ISSUE TITLE
Represent commits in the database

### ISSUE THREAD

**Issue by 0robustus1** [ontohub/ontohub#400]
As per #365 and #397 we should create a Commit model.

Corresponding to #350 this would be a FOIS-issue.

A commit model should have:

- commit oid
- datetime field which corresponds to the commits timestamp
- belongs to author (which is a Person, see #218)
- a many relation towards everything that can have a commit (LinkVersion, OntologyVersion, ....). This would probably be a polymorphic habtm.

Are there any additions , which aren't listed currently?

**Comment by SGraef** [comment]
we have this feature
