### ISSUE TITLE
add proof status information for proof goals

### ISSUE THREAD

**Issue by tillmo** [ontohub/ontohub#50]
proof goals are sentences with `is_axiom=false`.

In Hets, we have the following proof status information:

```
-- | data type representing the proof status for a goal
data ProofStatus proof_tree = ProofStatus
    { goalName :: String
    , goalStatus :: GoalStatus
    , usedAxioms :: [String] -- ^ used axioms
    , usedProver :: String -- ^ name of prover
    , proofTree :: proof_tree
    , usedTime :: TimeOfDay
    , tacticScript :: TacticScript }
    deriving (Show, Eq, Ord)
```

This should go into a new database table

**Comment by eugenk** [comment]
There is an inconsistency between the diagram and the text in the dataform ontology of the more recent SZS ontology: The diagram says `Sol` to Solution while the text says `Sln`. For ontohub, I use the id from the text. The new SZS ontology is uploaded at [ontohub/meta/proof_statuses.owl@87c615c](https://ontohub.org/repositories/meta/87c615cd8777b4fd5fc67ce5c066483e638f3902/show/proof_statuses.owl)
