### ISSUE TITLE
reprocess processing jobs on sidekiq restart

### ISSUE THREAD

**Issue by 0robustus1** [ontohub/ontohub#663]
On deployment machines a restart of sidekiq could happen while ontologies/jobs are processing. We should restart those jobs on restarting sidekiq.

**Comment by ebolloff** [comment]
When you kill the process with `kill -TERM`, the jobs are restarted afterwards.
From the sidekiq Signals wiki:

> It will stop accepting new work, but continue working on current messages (as with USR1). Any workers that do not finish within the timeout are forcefully terminated and their messages are pushed back to Redis to be executed again when Sidekiq starts up.

So this isn't relevant anymore.

**Comment by 0robustus1** [comment]
Just to slightly chime in here ;) From my own experience with worker-services like this (not necessarily sidekiq, but also sidekiq itself). This auto-restart mechanic doesn't always reliably work. You might want to at least employ a cronjob-kill-script that regularly kills (with `-9` if necessary) leftover processes. But this is just a suggestion, if you don't experience any problems that might come from this anymore, it might just work for you :)
