### ISSUE TITLE
Repair or remove entities search.

### ISSUE THREAD

**Issue by nning** [ontohub/ontohub#800]
We have some code for entities searching (`app/models/entity/searching.rb`, `app/controllers/entities_search_controller.rb` and corresponding views) and I'm not sure, if we need it anymore. The route to the entities search controller seems not to be linked. If you call it manually, it raises an exception.

So we should decide if we need it anymore and delete or repair it.

**Comment by eugenk** [comment]
We don't have an entity search any more.
