### ISSUE TITLE
After seeds there are pending versions

### ISSUE THREAD

**Issue by 0robustus1** [ontohub/ontohub#907]
After completing the seeds in staging, there are OntologyVersions which have a state of `"pending"`. Interestingly they all are corresponding to ontologies which are single ontologies in distributed ontologies.

Here is the workflow:

- `rake db:migrate:clean`
- `rake sidekiq:start && rake sunspot:solr:start`
- `rake db:seed`

**Comment by ebolloff** [comment]
This isn't relevant anymore. On @eugenk and my machines is everything ok.
